Repository SOM-Timer/som_timer_fe, pull requests merged in 2020-11, with the labels that each got.

#71 Feature/abd audio notification
  src/Components/CountdownTimer/CountdownTimer.js
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.test.js
  src/Context/SettingsContext.js
  src/apiCalls.js
  src/assets/audio/birdChord.mp3
  src/assets/audio/chordCliff.mp3
  src/assets/audio/gong.mp3
  src/assets/audio/goodOldSynths.mp3
  src/assets/audio/levelUp.mp3
  src/assets/audio/pianoDreams.mp3
  src/helpers/audioHelper.js
Labels: FE, Phase 4, feature/enhancement, testing

#80 Testing/rw test coverage
  .vscode/settings.json
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/ContentDelivery/ContentDelivery.js
  src/Components/ContentSelection/ContentSelection.js
  src/Components/ContentSelection/ContentSelection.test.js
  src/Components/CountdownTimer/CountdownTimer.js
  src/Components/CountdownTimer/CountdownTimer.test.js
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.test.js
  src/helpers/notificationHelpers.js
Labels: FE, Phase 4, testing

#84 Bug/rw audio settings
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.test.js
  src/Context/SettingsContext.js
  src/assets/audio/balineseGong.mp3
  src/assets/audio/reverbSplash.mp3
  src/helpers/audioHelper.js
Labels: FE, Phase 5, bug

#85 Feature/jkw mood rating
  src/Components/App/App.test.js
  src/Components/ContentDelivery/ContentDelivery.js
  src/Components/ContentDelivery/ContentDelivery.test.js
  src/Components/ContentSelection/ContentSelection.js
  src/Components/ContentSelection/ContentSelection.test.js
  src/Components/CountdownTimer/CountdownTimer.js
  src/Components/CountdownTimer/CountdownTimer.test.js
  src/Components/HomeContainer/HomeContainer.js
  src/Components/HomeContainer/HomeContainer.test.js
  src/Components/MoodRating/MoodRating.js
  src/Components/MoodRating/MoodRating.module.scss
  src/Components/MoodRating/MoodRating.test.js
  src/Context/SessionContext.js
  src/apiCalls.js
  src/assets/moodIcons/moodIcon1.png
  src/assets/moodIcons/moodIcon2.png
  src/assets/moodIcons/moodIcon3.png
  src/assets/moodIcons/moodIcon4.png
  src/assets/moodIcons/moodIcon5.png
  src/index.js
Labels: FE, Phase 5, feature/enhancement, html/CSS, testing

#89 Feature/jkw focus modal
  src/Components/App/App.test.js
  src/Components/ContentDelivery/ContentDelivery.js
  src/Components/ContentDelivery/ContentDelivery.module.scss
  src/Components/FocusModal/FocusModal.js
  src/Components/FocusModal/FocusModal.module.scss
  src/Components/FocusModal/FocusModal.test.js
  src/Components/HomeContainer/HomeContainer.js
  src/Components/MoodRating/MoodRating.js
  src/Components/MoodRating/MoodRating.module.scss
  src/Components/MoodRating/MoodRating.test.js
Labels: FE, Phase 5, feature/enhancement

#87 Feature/rw customize notification
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/CountdownTimer/CountdownTimer.js
  src/helpers/notificationHelpers.js
Labels: FE, Phase 5, bug, feature/enhancement

#90 Style/abd style cleanup
  .vscode/settings.json
  src/Components/About/About.js
  src/Components/About/About.module.scss
  src/Components/About/About.test.js
  src/Components/App/App.test.js
  src/Components/ContentDelivery/ContentDelivery.js
  src/Components/ContentDelivery/ContentDelivery.module.scss
  src/Components/ContentDelivery/ContentDelivery.test.js
  src/Components/ContentSelection/ContentSelection.js
  src/Components/ContentSelection/ContentSelection.module.scss
  src/Components/CountdownTimer/CountdownTimer.js
  src/Components/CountdownTimer/CountdownTimer.module.scss
  src/Components/FocusModal/FocusModal.js
  src/Components/FocusModal/FocusModal.module.scss
  src/Components/FocusModal/FocusModal.test.js
  src/Components/Header/Header.module.scss
  src/Components/MoodRating/MoodRating.js
  src/Components/MoodRating/MoodRating.module.scss
  src/Components/MoodRating/MoodRating.test.js
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.module.scss
  src/Components/Stats/Stats.js
  src/Components/Stats/Stats.module.scss
  src/Context/VideoContext.js
  src/assets/content/yogaContentIcon.png
  src/index.scss
  src/style/mixins.scss
  src/style/variables.scss
Labels: FE, Phase 5, assets, bug, html/CSS

#91 Documentation/rw readme
  README.md
Labels: FE, Phase 5, documentation

#96 Feature/rw random notification
  src/Components/CountdownTimer/CountdownTimer.js
  src/Components/Settings/Settings.js
  src/apiCalls.js
  src/helpers/audioHelper.js
Labels: FE, feature/enhancement

#99 Feature/rw mood settings
  src/Components/App/App.test.js
  src/Components/ContentDelivery/ContentDelivery.js
  src/Components/ContentDelivery/ContentDelivery.module.scss
  src/Components/CountdownTimer/CountdownTimer.js
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.module.scss
  src/Components/Settings/Settings.test.js
  src/Context/SettingsContext.js
  src/apiCalls.js
Labels: FE, Sprint 11/20, feature/enhancement

#102 Bug/abd timer persist alternate
  src/Components/About/About.js
  src/Components/About/About.test.js
  src/Components/App/App.js
  src/Components/App/App.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.test.js
  src/Components/HomeContainer/HomeContainer.js
  src/Components/PageNotFound/PageNotFound.js
  src/Components/PageNotFound/PageNotFound.test.js
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.test.js
  src/Components/Stats/Stats.js
  src/Components/Stats/Stats.test.js
  src/helpers/audioHelper.js
Labels: Sprint 11/20, bug, testing

#103 Feature/jkw login screen
  public/index.html
  src/Components/Login/Login.js
  src/Components/Login/Login.module.scss
  src/Components/Login/Login.test.js
Labels: FE, Sprint 11/20, feature/enhancement, html/CSS, testing

#105 Feature/abd timer persist proptypes
  src/Components/About/About.js
  src/Components/App/App.js
  src/Components/Header/Header.js
  src/Components/PageNotFound/PageNotFound.js
  src/Components/Settings/Settings.js
  src/Components/Stats/Stats.js
Labels: FE, Sprint 11/20, feature/enhancement

#107 Feature/abd implement users
  package-lock.json
  public/index.html
  src/Components/About/About.test.js
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/ContentDelivery/ContentDelivery.test.js
  src/Components/FocusModal/FocusModal.test.js
  src/Components/HomeContainer/HomeContainer.js
  src/Components/HomeContainer/HomeContainer.test.js
  src/Components/Login/Login.js
  src/Components/Login/Login.module.scss
  src/Components/Login/Login.test.js
  src/Components/PageNotFound/PageNotFound.test.js
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.module.scss
  src/Components/Settings/Settings.test.js
  src/Context/UserContext.js
  src/apiCalls.js
  src/index.js
Labels: FE, feature/enhancement, testing

#108 Feature/rw update endpoints
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/FocusModal/FocusModal.js
  src/Components/FocusModal/FocusModal.test.js
  src/Components/Login/Login.js
  src/Components/Login/Login.test.js
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.test.js
  src/Context/SettingsContext.js
  src/Context/UserContext.js
  src/apiCalls.js
  src/index.js
Labels: FE, Sprint 11/20, feature/enhancement

#109 Feature/jkw statistics initial
  package-lock.json
  package.json
  src/Components/App/App.test.js
  src/Components/Stats/Stats.js
  src/Components/Stats/Stats.module.scss
  src/Components/Stats/Stats.test.js
  src/apiCalls.js
Labels: FE, feature/enhancement, html/CSS, testing
