Repository SOM-Timer/som_timer_fe, pull requests merged in 2020-10, with the labels that each got.

#21 Style/abd create scss variables
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/index.scss
  src/style/variables.scss
Labels: Phase 2, html/CSS

#22 Feature/rw content delivery
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/ContentDelivery/ContentDelivery.js
  src/Components/ContentDelivery/ContentDelivery.scss
  src/Components/ContentDelivery/ContentDelivery.test.js
  src/Context/VideoContext.js
  src/index.js
  src/index.scss
  src/style/mixins.scss
  src/style/variables.scss
Labels: FE, feature/enhancement, html/CSS, testing

#28 Feature/abd header
  src/Components/App/App.js
  src/Components/Header/Header.js
  src/Components/Header/Header.module.scss
  src/Components/Header/Header.test.js
  src/assets/metatronsSettings.png
  src/index.js
  src/style/variables.scss
Labels: FE, Phase 2, feature/enhancement, html/CSS, testing

#31 Feature/rw container component
  src/Components/App/App.js
  src/Components/ContentDelivery/ContentDelivery.js
  src/Components/ContentDelivery/ContentDelivery.module.scss
  src/Components/ContentDelivery/ContentDelivery.test.js
  src/Components/HomeContainer/HomeContainer.js
  src/Components/HomeContainer/HomeContainer.module.scss
  src/Components/HomeContainer/HomeContainer.test.js
  src/Context/ViewContext.js
Labels: FE, Phase 2, feature/enhancement

#32 Feature/abd content selection
  src/Components/ContentSelection/ContentSelection.js
  src/Components/ContentSelection/ContentSelection.module.scss
  src/Components/ContentSelection/ContentSelection.test.js
  src/Components/HomeContainer/HomeContainer.js
Labels: FE, Phase 2, feature/enhancement, html/CSS, testing

#33 Feature/jkw settings
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/HomeContainer/HomeContainer.test.js
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.module.scss
  src/Components/Settings/Settings.test.js
  src/Components/Timer/Timer.js
  src/Components/Timer/Timer.test.js
  src/Context/SettingsContext.js
Labels: FE, Phase 2, feature/enhancement, testing

#36 Feature/rw about page
  src/Components/About/About.js
  src/Components/About/About.module.scss
  src/Components/About/About.test.js
Labels: FE, Phase 2, feature/enhancement

#37 Feature/rw home views
  src/Components/ContentSelection/ContentSelection.js
  src/Components/Timer/Timer.js
Labels: FE, Phase 2, feature/enhancement

#49 Implement routes and reorder imports #39
  src/Components/App/App.js
  src/Components/Header/Header.js
Labels: FE, feature/enhancement

#54 Feature/rw 404 and stats
  .travis.yml
  src/Components/About/About.js
  src/Components/About/About.module.scss
  src/Components/App/App.js
  src/Components/PageNotFound/PageNotFound.js
  src/Components/PageNotFound/PageNotFound.module.scss
  src/Components/PageNotFound/PageNotFound.test.js
  src/Components/Stats/Stats.js
  src/Components/Stats/Stats.module.scss
  src/Components/Stats/Stats.test.js
  src/assets/burnout3.jpg
  src/index.js
Labels: FE, Phase 3, feature/enhancement

#56 Style/abd style unification
  src/Components/About/About.js
  src/Components/About/About.module.scss
  src/Components/About/About.test.js
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/App/App.scss
  src/Components/ContentDelivery/ContentDelivery.js
  src/Components/ContentDelivery/ContentDelivery.module.scss
  src/Components/ContentSelection/ContentSelection.js
  src/Components/ContentSelection/ContentSelection.module.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.module.scss
  src/Components/HomeContainer/HomeContainer.js
  src/Components/HomeContainer/HomeContainer.test.js
  src/Components/PageNotFound/PageNotFound.js
  src/Components/PageNotFound/PageNotFound.module.scss
  src/Components/Settings/Settings.js
  src/Components/Settings/Settings.module.scss
  src/Components/Stats/Stats.js
  src/Components/Stats/Stats.module.scss
  src/Components/Stats/Stats.test.js
  src/Components/Timer/Timer.js
  src/Components/Timer/Timer.module.scss
  src/Components/Timer/Timer.test.js
  src/assets/content/meditationContentIcon.png
  src/assets/content/somaticContentIcon.png
  src/assets/metatronsSettings.png
  src/assets/navbar/aboutNavIcon.png
  src/assets/navbar/settingsNavIcon.png
  src/assets/navbar/statsNavIcon.png
  src/assets/navbar/timerNavIcon.png
  src/assets/timer/pauseTimerIcon.png
  src/assets/timer/playTimerIcon.png
  src/assets/timer/resetTimerIcon.png
  src/assets/timer/skipTimerIcon.png
Labels: FE, Phase 3, html/CSS

#65 Bug/jkw countdown timer context
  src/Components/CountdownTimer/CountdownTimer.js
  src/Components/CountdownTimer/CountdownTimer.module.scss
  src/Components/CountdownTimer/CountdownTimer.test.js
  src/Components/HomeContainer/HomeContainer.test.js
  src/Components/Timer/Timer.js
  src/Context/SettingsContext.js
Labels: FE, bug, sprint 4

#66 Feature/rw timer keyframes
  src/Components/CountdownTimer/CountdownTimer.js
  src/Components/CountdownTimer/CountdownTimer.module.scss
Labels: FE, feature/enhancement, sprint 4

#69 Feature/jkw push notifications
  src/Components/About/About.js
  src/Components/App/App.js
  src/Components/CountdownTimer/CountdownTimer.js
  src/sw-custom.js
Labels: FE, feature/enhancement, sprint 4

#70 Update README #61
  README.md
Labels: FE, documentation
